### ISSUE TITLE
New files not found until scan interval modified

### ISSUE THREAD

**Issue by holmesrichards** [albertlauncher/plugins#126] opened 2023-10-14 12:30 UTC
#### Description
New files/directories are not findable by Files plugin for some days unless Scan Interval is modified.

#### Expected behavior
When a new file or directory is created, it should be findable by Files fairly soon after.

#### Steps to reproduce
1. Set up Files plugin like this:

![image](https://github.com/albertlauncher/albert/assets/56895621/ad358d46-4705-4b2c-a906-3d937075e619)

2. Create a new file or directory
3. Go to bed, get up the next day
4. In Albert, type in the new file name. It is not found.
5. Open the Files settings, change "Scan interval" to 10 min and immediately back to 5 min.
6. In Albert, type in the new file name. It is found.

(If scan interval is not changed, the new file is eventually findable, but it might not be for several days.)

#### Source
http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_22.04/

#### Debug output

<details>

```
$ albert -d
        Albert version: 0.21.0
            Build date: May 18 2023 15:51:19
            Qt version: 6.2.4
             Build ABI: x86_64-little_endian-lp64
  Arch (build/current): x86_64/x86_64
 Kernel (type/version): linux/5.15.0-84-generic
                    OS: Linux Mint 21.2
     OS (type/version): linuxmint/21.2
 $QT_QPA_PLATFORMTHEME: qt5ct
         Platform name: xcb
                  Font: Ubuntu,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1
       Binary location: /usr/bin/albert
                  $PWD: /home/rsholmes
                $SHELL: /bin/bash
                 $LANG: en_US.UTF-8
              Language: English
                Locale: en_US
     $XDG_SESSION_TYPE: x11
  $XDG_CURRENT_DESKTOP: X-Cinnamon
      $DESKTOP_SESSION: cinnamon
  $XDG_SESSION_DESKTOP: cinnamon
            Icon theme: Mint-Y-Blue
08:23:59 [crit:albert] Application has not been terminated graciously
08:23:59 [debg:albert] Checking for a running instance…
08:23:59 [info:albert] There is another instance of albert running.

```

</details>

**Comment by ManuelSchneid3r** [comment] 2023-10-16 07:28
> 0.21.0

please update. were at 0.22.14

**Comment by ManuelSchneid3r** [comment] 2023-10-16 20:09
Probably a dupe of #96. Let me know if the update fixes this issue for you.

**Closed by ManuelSchneid3r** 2023-10-16 20:09 UTC

**Comment by holmesrichards** [comment] 2023-10-16 20:23
I've installed albert 0.22.14. But the Files plugin still shows version 1.4. In the above issue it says it should be 1.6. I can't find where it's documented how to upgrade the plugin. In particular https://albertlauncher.github.io/extending/ tells how to write a plugin, but not how to install or upgrade one.

**Comment by holmesrichards** [comment] 2023-10-16 20:32
Ah, OK, I now see Files 1.7. Presumably OK now.

**Comment by ManuelSchneid3r** [comment] 2023-10-16 20:32
> I've installed albert 0.22.14. But the Files plugin still shows version 1.4. In the above issue it says it should be 1.6. (Or is that only for the master build? Is that bug fix not in the stable release yet?)

actually it should be 1.7. have you installed `albert` and `albert-master`?
