### ISSUE TITLE
Applications plugins cannot find pycharm

### ISSUE THREAD

**Issue by arcan1s** [albertlauncher/plugins#74] opened 2023-01-05 17:21 UTC
If I would like to try to find `pycharm`, it doesn't show anything

![изображение](https://user-images.githubusercontent.com/2799891/210841297-c8baeb8f-b73d-4b61-88b4-19a79584f046.png)

desktop file looks like

```
[Desktop Entry]
Type=Application
Name=PyCharm Professional Edition
Icon=pycharm
Comment=Python IDE for Professional Developers.
Exec=pycharm %f
Terminal=false
Categories=Development;IDE;Python;
StartupNotify=true
StartupWMClass=jetbrains-pycharm
```

`Charm` (case sensitive) search doesn't work either. However it is possible to find by typing `pycharm` instead (or even `professional`). Fuzzy search option has no effect

![изображение](https://user-images.githubusercontent.com/2799891/210841805-c3af380b-2034-49a1-9571-a18f7d76d38c.png)

**Comment by ManuelSchneid3r** [comment] 2023-01-05 21:01
This is somewhat by intention. Currently there are only two search indizes, an ngram fuzzy index and a prefix match. the rationale is because they are fast _af_. If you are a computer science dude you probably know why. But well yes not always holds convenience < performance. This is future work.

**Comment by arcan1s** [comment] 2023-01-05 22:08
in terms of performance it might make sense to load from indices fast enough and do full text-search after that in background. Also considering that (unless you are going to load all applications in /bin which would really slow down) there are not so much applications installed for average user, background load shouldn't be much expensive

**Comment by ManuelSchneid3r** [comment] 2023-01-07 17:22
The index is a sorted array with a log(n) binary search for the prefix search. The comparison operator to sort and search is lexicographic comparison. Substings are simply no prefixes and therefore this won't work. Sure tolerance is a thing to think about, but it has no high priority because the cost of results cluttering is high imho. For pycharm this may come in handy bit for >99% of the cases this makes no sense. You would not use harm or arm to search for pycharm. This cases would be covered though. We could rather implement some other approach to generate the search stings to use for app names. (such as others suggested to eg find FireFox by ff or pycharm by pc )

**Comment by ManuelSchneid3r** [comment] 2023-01-22 13:49
This is technically not a bug. Therefore im closing this one.

**Closed by ManuelSchneid3r** 2023-01-22 13:49 UTC
Labels: Maintainer wanted
